### ISSUE TITLE
Error when runing function test_IKE_Blip2OPT_VQA() in multimodal_edit.py

### ISSUE THREAD

**Issue by yaohui120** [zjunlp/EasyEdit#156]
I'm trying to reproduce the result of method IKE on VQA dataset. But it appears the error:
```
Editing dataset:  75%|███████▌  | 1574/2093 [1:06:03<21:46,  2.52s/it]
Traceback (most recent call last):
  File "/mnt/Data/EasyEdit-main/multimodal_edit.py", line 737, in <module>
    test_IKE_Blip2OPT_VQA()
  File "/mnt/Data/EasyEdit-main/multimodal_edit.py", line 506, in test_IKE_Blip2OPT_VQA
    metrics, edited_model, _ = editor.edit_dataset(
  File "/mnt/Data/EasyEdit-main/easyeditor/editors/multimodal_editor.py", line 463, in edit_dataset
    "post": compute_icl_multimodal_edit_quality(self.model, self.model_name, self.hparams, self.tok, icl_examples,
  File "/mnt/Data/EasyEdit-main/easyeditor/evaluate/evaluate.py", line 329, in compute_icl_multimodal_edit_quality
    locality_image_acc, _ = icl_multimodal_lm_eval(model, model_name, hparams, tok, icl_examples,
  File "/mnt/Data/EasyEdit-main/easyeditor/evaluate/evaluate.py", line 348, in icl_multimodal_lm_eval
    samples = prepare_multimodal_edit(hparams, tokenizer, target, [''.join(icl_examples) + f'{x}'], image) 
  File "/mnt/Data/EasyEdit-main/easyeditor/evaluate/evaluate.py", line 370, in prepare_multimodal_edit
    target = tok([' ' + target_ if target_[0] != ' ' else target_ for target_ in target], add_special_tokens=False, return_tensors="pt",)["input_ids"]
  File "/mnt/Data/EasyEdit-main/easyeditor/evaluate/evaluate.py", line 370, in <listcomp>
    target = tok([' ' + target_ if target_[0] != ' ' else target_ for target_ in target], add_special_tokens=False, return_tensors="pt",)["input_ids"]
IndexError: string index out of range
```

**Comment by zxlzr** [comment]
Hi, we will check the code and response to you asap.

**Comment by tbozhong** [comment]
Thank you for your interest in our work.

Due to the presence of null values in the dataset, which was formatted for EasyEdit, your code may have encountered errors. We have now updated the dataset on Google Drive to address this issue.

Please download the latest dataset and code to reproduce the results.

**Comment by yaohui120** [comment]
Well, I will try to run it on the latest dataset. Thanks!
