### ISSUE TITLE
Using MEMIT with multiple GPU's

### ISSUE THREAD

**Issue by MaximIfergan** [zjunlp/EasyEdit#204]
Hello!

First of all, thank you for this great repo.  
I have some trouble running MEMIT on Qwen with "model_parallel: true" using the default parameters with "device: 0". I am running the program on Linux Debian-11 with Cuda 12.1 on 4 NVIDIA L4 parallel GPUs.
This error occurs while running:

Traceback (most recent call last):
  File "/home/maxim758/MKE/EasyEdit/easyeditor/editors/editor.py", line 280, in edit
    edited_model, weights_copy = self.apply_algo(
  File "/home/maxim758/MKE/EasyEdit/easyeditor/models/memit/memit_main.py", line 46, in apply_memit_to_model
    deltas = execute_memit(model, tok, requests, hparams, cache_template=cache_template)
  File "/home/maxim758/MKE/EasyEdit/easyeditor/models/memit/memit_main.py", line 140, in execute_memit
    cur_z = compute_z(
  File "/home/maxim758/MKE/EasyEdit/easyeditor/models/memit/compute_z.py", line 135, in compute_z
    logits = model(**input_tok).logits
  File "/opt/conda/envs/EasyEdit/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/EasyEdit/lib/python3.9/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/maxim758/.cache/huggingface/modules/transformers_modules/Qwen/Qwen-7B/ef3c5c9c57b252f3149c1408daf4d649ec8b6c85/modeling_qwen.py", line 1043, in forward
    transformer_outputs = self.transformer(
  File "/opt/conda/envs/EasyEdit/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/maxim758/.cache/huggingface/modules/transformers_modules/Qwen/Qwen-7B/ef3c5c9c57b252f3149c1408daf4d649ec8b6c85/modeling_qwen.py", line 891, in forward
    outputs = block(
  File "/opt/conda/envs/EasyEdit/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1547, in _call_impl
    hook_result = hook(self, args, result)
  File "/home/maxim758/MKE/EasyEdit/easyeditor/util/nethook.py", line 80, in retain_hook
    output = invoke_with_optional_args(
  File "/home/maxim758/MKE/EasyEdit/easyeditor/util/nethook.py", line 451, in invoke_with_optional_args
    return fn(*pass_args, **pass_kw)
  File "/home/maxim758/MKE/EasyEdit/easyeditor/models/memit/compute_z.py", line 112, in edit_output_fn
    cur_out[0][i, idx, :] += delta
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!

1) Is it possible to run MEMIT on parallel GPUs?
2) Do you encounter this problem or know how to fix it?

Thank You,
Maxim Ifergan.

**Comment by XeeKee** [comment]
I recommend you start with a single GPU, there is indeed an issue here, and we will fix it in the next few days

**Comment by XeeKee** [comment]
You can update to the latest code, set CUDA_VISIBLE_DEVICES to within two cards, set the device to 0.

**Comment by zxlzr** [comment]
hi, have you solved your issue yet？
