### ISSUE TITLE
MEND running error

### ISSUE THREAD

**Issue by Luoyang144** [zjunlp/EasyEdit#304]
I'm using archive from this [link](https://drive.google.com/drive/folders/1WyqsN-O5bpzzRvbYrVDJdVHdOu1x6mSB), here is log:
```
Traceback (most recent call last):
  File "/home/xx/Model-Edit/Baseline/knowledge_edit.py", line 231, in <module>
    metrics, edited_model, _ = editor.edit(
  File "/home/xxx/Model-Edit/Baseline/easyeditor/editors/editor.py", line 159, in edit
    return self.edit_requests(requests, sequential_edit, verbose, test_generation=test_generation, **kwargs)
  File "/home/xxx/Model-Edit/Baseline/easyeditor/editors/editor.py", line 335, in edit_requests
    edit_evaluation(all_metrics, request, edited_model, i, eval_metric, test_generation, icl_examples, **kwargs)
  File "/home/xxx/Model-Edit/Baseline/easyeditor/editors/editor.py", line 310, in edit_evaluation
    "post": compute_edit_quality(edited_model, self.model_name, self.hparams, self.tok, request, self.hparams.device, eval_metric=eval_metric, test_generation=test_generation),
  File "/home/xxx/Model-Edit/Baseline/easyeditor/evaluate/evaluate.py", line 93, in compute_edit_quality
    ret['fluency'] = test_generation_quality(model=model,tok=tok,prefixes=rewrite_prompts if isinstance(rewrite_prompts,list) else [rewrite_prompts,], max_out_len=100, vanilla_generation=False)
  File "/home/xxx/Model-Edit/Baseline/easyeditor/evaluate/evaluate_utils.py", line 187, in test_generation_quality
    gen_texts = generate_fast(
  File "/home/xxx/Model-Edit/Baseline/easyeditor/util/generate.py", line 128, in generate_fast
    logits, past_key_values = model_out.logits, model_out.past_key_values
AttributeError: 'Tensor' object has no attribute 'logits'
```
Any idea?

**Comment by XeeKee** [comment]
Thank you very much for your attention to EasyEdit. We have already fixed this bug.
in 3eb902cb8e8fa84a6a0f178be3fe99112608b2bd
