### ISSUE TITLE
Index out of bound error with chatglm2-6b

### ISSUE THREAD

**Issue by peixin-lin** [zjunlp/EasyEdit#34]
I tried to follow the demo in /tutorial-notebooks with the model chatglm2-6b using ROME or MEMIT but both stop by an index out of bound error. What caused this error? How can I work around it?

**The code I used is as below:**
```
import os

from easyeditor import BaseEditor
from easyeditor import ROMEHyperParams


PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))

prompts = ['Ray Charles, the',
            'Grant Hill is a professional',
            'The law in Ikaalinen declares the language'
            ]
ground_truth = ['piano',
                'basketball',
                'Finnish'
                ]
target_new = ['violin',
              'soccer',
              'Swedish'
              ]
subject = ['Ray Charles',
            'Grant Hill',
            'Ikaalinen'
            ]

hparams = ROMEHyperParams.from_hparams(os.path.join(PROJECT_PATH, 'hparams/ROME/chatglm2-6b.yaml'))
editor = BaseEditor.from_hparams(hparams)
metrics, edited_model, _ = editor.edit(
    prompts=prompts,
    ground_truth=ground_truth,
    target_new=target_new,
    subject=subject,
    keep_original_weight=True
)

print(metrics)


print('*'*20)

from transformers import GPT2Tokenizer
from transformers import GPT2LMHeadModel

# tokenizer = GPT2Tokenizer.from_pretrained('./hugging_cache/gpt2-xl')
tokenizer = GPT2Tokenizer.from_pretrained('/home/workspace/pretrain-model/THUDM/chatglm2-6b')
tokenizer.pad_token_id = tokenizer.eos_token_id
tokenizer.padding_side='left'
generation_prompts = [
    "Ray Charles, the",
    "The law in Ikaalinen declares the language"
]

model = GPT2LMHeadModel.from_pretrained('/home/workspace/pretrain-model/THUDM/chatglm2-6b').to('cuda')
batch = tokenizer(generation_prompts, return_tensors='pt', padding=True, max_length=30)

pre_edit_outputs = model.generate(
    input_ids=batch['input_ids'].to('cuda'),
    attention_mask=batch['attention_mask'].to('cuda'),
    max_length=10
)

post_edit_outputs = edited_model.generate(
    input_ids=batch['input_ids'].to('cuda'),
    attention_mask=batch['attention_mask'].to('cuda'),
    max_length=10
)
```

**The error message for MEMIT is as below:**

```
Traceback (most recent call last):
  File "/home/workspace/knowledge_edit/EasyEdit-main/demo.py", line 28, in <module>
    metrics, edited_model, _ = editor.edit(
  File "/home/workspace/knowledge_edit/EasyEdit-main/easyeditor/editors/editor.py", line 242, in edit
    edited_model, weights_copy = self.apply_algo(
  File "/home/workspace/knowledge_edit/EasyEdit-main/easyeditor/models/memit/memit_main.py", line 46, in apply_memit_to_model
    deltas = execute_memit(model, tok, requests, hparams, cache_template=cache_template)
  File "/home/workspace/knowledge_edit/EasyEdit-main/easyeditor/models/memit/memit_main.py", line 141, in execute_memit
    cur_z = compute_z(
  File "/home/workspace/knowledge_edit/EasyEdit-main/easyeditor/models/memit/compute_z.py", line 126, in compute_z
    logits = model(**input_tok).logits
  File "/opt/anaconda3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b/8fd7fba285f7171d3ae7ea3b35c53b6340501ed1/modeling_chatglm.py", line 934, in forward
    transformer_outputs = self.transformer(
  File "/opt/anaconda3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b/8fd7fba285f7171d3ae7ea3b35c53b6340501ed1/modeling_chatglm.py", line 830, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "/opt/anaconda3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b/8fd7fba285f7171d3ae7ea3b35c53b6340501ed1/modeling_chatglm.py", line 640, in forward
    layer_ret = layer(
  File "/opt/anaconda3.10/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1547, in _call_impl
    hook_result = hook(self, args, result)
  File "/home/workspace/knowledge_edit/EasyEdit-main/easyeditor/util/nethook.py", line 80, in retain_hook
    output = invoke_with_optional_args(
  File "/home/workspace/knowledge_edit/EasyEdit-main/easyeditor/util/nethook.py", line 451, in invoke_with_optional_args
    return fn(*pass_args, **pass_kw)
  File "/home/workspace/knowledge_edit/EasyEdit-main/easyeditor/models/memit/compute_z.py", line 103, in edit_output_fn
    cur_out[0][i, idx, :] += delta
IndexError: index 12 is out of bounds for dimension 1 with size 7
```

**The error message for ROME is as below**:
```
Traceback (most recent call last):
  File "/home/workspace/knowledge_edit/EasyEdit-main/demo.py", line 28, in <module>
    metrics, edited_model, _ = editor.edit(
  File "/home/workspace/knowledge_edit/EasyEdit-main/easyeditor/editors/editor.py", line 242, in edit
    edited_model, weights_copy = self.apply_algo(
  File "/home/workspace/knowledge_edit/EasyEdit-main/easyeditor/models/rome/rome_main.py", line 41, in apply_rome_to_model
    deltas = execute_rome(model, tok, request, hparams)
  File "/home/workspace/knowledge_edit/EasyEdit-main/easyeditor/models/rome/rome_main.py", line 104, in execute_rome
    left_vector: torch.Tensor = compute_u(
  File "/home/workspace/knowledge_edit/EasyEdit-main/easyeditor/models/rome/compute_u.py", line 85, in compute_u
    cur_repr = repr_tools.get_reprs_at_word_tokens(
  File "/home/workspace/knowledge_edit/EasyEdit-main/easyeditor/models/rome/repr_tools.py", line 32, in get_reprs_at_word_tokens
    return get_reprs_at_idxs(
  File "/home/workspace/knowledge_edit/EasyEdit-main/easyeditor/models/rome/repr_tools.py", line 164, in get_reprs_at_idxs
    _process(tr.input, batch_idxs, "in")
  File "/home/workspace/knowledge_edit/EasyEdit-main/easyeditor/models/rome/repr_tools.py", line 147, in _process
    to_return[key].append(cur_repr[i][idx_list].mean(0))
IndexError: index 15 is out of bounds for dimension 0 with size 15
```

**Comment by pengzju** [comment]
It looks like you are using the `ROME` to edit `ChatGLM`, this feature is still under development. Please look forward to the new version of EasyEdit. 😊

**Comment by peixin-lin** [comment]
> It looks like you are using the `ROME` to edit `ChatGLM`, this feature is still under development. Please look forward to the new version of EasyEdit. 😊

Well, I saw this file `hparams/ROME/chatglm2-6b.yaml` so I tried with it. 
When will you release the new version? Will Baichuan-7b also be supported by that time?

**Comment by pengzju** [comment]
1. `Baichuan-7b` is already supported. You can see it here: https://github.com/zjunlp/EasyEdit#current-implementation
2. The new version will be released as soon as possible. Thank you for your patience

**Comment by ChrisXULC** [comment]
Hi, will Qwen-chat-7b also be supported in the new version?

**Comment by zxlzr** [comment]
Qwen will be supported in the next version.

**Comment by XeeKee** [comment]
Thank you for your attention, EasyEdit currently supports chatglm2，If you have any other questions, please feel free to leave a message.

**Comment by pengzju** [comment]
If your problem has been resolved, please help close this issue.
