### ISSUE TITLE
unexpected_keys assertion error when running SERAC

### ISSUE THREAD

**Issue by BUGLI27** [zjunlp/EasyEdit#364]
Hi, I'm having some issues running the SERAC methed. I took a closer look at the https://github.com/zjunlp/EasyEdit/issues/261, but the issue is still not resolved 
I tried `JackFram/llama-160m`, but the error still persists when running SERAC method and the error message is as follows:

```txt
metrics, edited_model, _ = editor.edit(
  File "/home/hli/project/KnowledgeEdit/EasyEdit/examples/../easyeditor/editors/editor.py", line 271, in edit
    edited_model, weights_copy = self.apply_algo(
  File "/home/hli/project/KnowledgeEdit/EasyEdit/examples/../easyeditor/models/serac/serac_main.py", line 68, in apply_to_model
    self.init_model(model, tok, hparams)
  File "/home/hli/project/KnowledgeEdit/EasyEdit/examples/../easyeditor/models/serac/serac_main.py", line 34, in init_model
    self.alg.load_state_dict(d["model"], False)
  File "/home/hli/project/KnowledgeEdit/EasyEdit/examples/../easyeditor/trainer/algs/SERAC.py", line 123, in load_state_dict
    assert len(res.unexpected_keys) == 0, print(res.unexpected_keys)
AssertionError: None 
```
And the ouput of res.unexpected_keys is:

> ['replacement.model.layers.0.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.1.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.2.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.3.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.4.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.5.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.6.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.7.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.8.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.9.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.10.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.11.self_attn.rotary_emb.inv_freq']

I checked the code and found that this error was caused by
```python
d = torch.load(params.archive, map_location='cpu')
self.alg.load_state_dict(d["model"], False)
```
and the params.archive was set to the path of the `JackFram/llama-160m`.

Do you have any ideas to solve this? Thank you.

**Comment by XeeKee** [comment]
I tried, but I couldn't reproduce your issue. Could you tell me where you downloaded the LLaMA2 model, or provide me with more information?

**Comment by BUGLI27** [comment]
I download Llama-2-7B from [shakechen/Llama-2-7b-hf](https://www.modelscope.cn/models/shakechen/Llama-2-7b-hf/files), and there is part of SERAC hparams.

```yaml
# Model
alg_name: "SERAC"
archive: ./results/models/SERAC/llama-2-7b.bk
device: 0
model_name: /models/meta-llama/llama-2-7b

model_class: LlamaForCausalLM
small_name: /models/JackFram/llama-160m
tokenizer_class: LlamaTokenizer
tokenizer_name: /models/meta-llama/llama-2-7b
cls_name: /models/distilbert/distilbert-base-cased
cls_class: AutoModel
inner_params: []
model_parallel: false
```

**Comment by XeeKee** [comment]
I noticed someone raised an issue saying this is incomplete on https://www.modelscope.cn/models/shakechen/Llama-2-7b-hf/feedback. Could you try downloading it from HF?

**Comment by BUGLI27** [comment]
OK, I'll give it a try, thank you.

**Comment by BUGLI27** [comment]
Llama-2-7b-hf from HF has been downloaded and tested, but the error persists.

Part of the error output is as follows.
```
./results/models/SERAC/llama-2-7b.bk
09/19/2024 14:39:58 - INFO - easyeditor.trainer.utils -   Set 13 dropout modules to p=0.0
09/19/2024 14:39:58 - INFO - easyeditor.trainer.utils -   Set 0 dropout modules to p=0.0
09/19/2024 14:40:06 - INFO - easyeditor.trainer.algs.SERAC -   Loaded model config doesn't match current model config.
09/19/2024 14:40:06 - INFO - easyeditor.trainer.algs.SERAC -   Loaded: LlamaConfig {
  "_name_or_path": "./hugging_cache/llama-2-7b",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 2048,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "pad_token_id": 0,
  "rms_norm_eps": 1e-05,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.36.2",
  "use_cache": true,
  "vocab_size": 32000
}

09/19/2024 14:40:06 - INFO - easyeditor.trainer.algs.SERAC -   Current: LlamaConfig {
  "_name_or_path": "/home/hli/models/Llama-2-7b-hf",
  "architectures": [
    "LlamaForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 4096,
  "model_type": "llama",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "pretraining_tp": 1,
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "rope_theta": 10000.0,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.36.2",
  "use_cache": true,
  "vocab_size": 32000
}

['replacement.model.layers.0.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.1.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.2.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.3.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.4.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.5.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.6.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.7.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.8.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.9.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.10.self_attn.rotary_emb.inv_freq', 'replacement.model.layers.11.self_attn.rotary_emb.inv_freq']
Traceback (most recent call last):
  File "/home/hli/project/KnowledgeEdit/EasyEdit/examples/run_knowedit_llama2.py", line 241, in <module>
    metrics, edited_model, _ = editor.edit(
  File "/home/hli/project/KnowledgeEdit/EasyEdit/examples/../easyeditor/editors/editor.py", line 305, in edit
    edited_model, weights_copy = self.apply_algo(
  File "/home/hli/project/KnowledgeEdit/EasyEdit/examples/../easyeditor/models/serac/serac_main.py", line 68, in apply_to_model
    self.init_model(model, tok, hparams)
  File "/home/hli/project/KnowledgeEdit/EasyEdit/examples/../easyeditor/models/serac/serac_main.py", line 34, in init_model
    self.alg.load_state_dict(d["model"], False)
  File "/home/hli/project/KnowledgeEdit/EasyEdit/examples/../easyeditor/trainer/algs/SERAC.py", line 146, in load_state_dict
    assert len(res.unexpected_keys) == 0, print(res.unexpected_keys)
AssertionError: None

**Comment by XeeKee** [comment]
Sorry, I am unable to reproduce your issue. Please try updating your code. If your code is already up to date, you might want to try using the code from three months ago. Additionally, you could try running it on a different machine.

**Comment by XeeKee** [comment]
https://drive.google.com/drive/folders/1rVWN7z05CHkIwbOJ5Cy3E0seWSpU6SeT
Here are some checkpoints I trained six months ago, you can give them a try.

**Comment by BUGLI27** [comment]
OK, I'll try it later, it should be a problem on my side. Thank you for your detailed reply.
