### ISSUE TITLE
OutOfMemoryError with MEMIT despite sufficient memory

### ISSUE THREAD

**Issue by shariqahn** [zjunlp/EasyEdit#449]
I am running run_zsre_llama2.py with MEMIT on 2  NVidia Volta V100 32GB GPUs, which I understand should be sufficient memory. However, I see the following error:
```
  0%|          | 0/1000 [00:00<?, ?it/s][Ahuggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

  0%|          | 0/1000 [00:01<?, ?it/s]

  0%|          | 0/1037 [00:31<?, ?it/s]
Traceback (most recent call last):
  File "/home/gridsan/shossain/EasyEdit/examples/run_zsre_llama2.py", line 93, in <module>
    metrics, edited_model, _ = editor.edit(
  File "/home/gridsan/shossain/EasyEdit/examples/../easyeditor/editors/editor.py", line 191, in edit
    return self.edit_requests(requests, sequential_edit, verbose, test_generation=test_generation, **kwargs)
  File "/home/gridsan/shossain/EasyEdit/examples/../easyeditor/editors/editor.py", line 379, in edit_requests
    edited_model, weights_copy, icl_examples = edit_func(request)
  File "/home/gridsan/shossain/EasyEdit/examples/../easyeditor/editors/editor.py", line 326, in edit_func
    edited_model, weights_copy = self.apply_algo(
  File "/home/gridsan/shossain/EasyEdit/examples/../easyeditor/models/memit/memit_main.py", line 46, in apply_memit_to_model
    deltas = execute_memit(model, tok, requests, hparams, cache_template=cache_template)
  File "/home/gridsan/shossain/EasyEdit/examples/../easyeditor/models/memit/memit_main.py", line 187, in execute_memit
    cov = get_cov(
  File "/home/gridsan/shossain/EasyEdit/examples/../easyeditor/models/memit/memit_main.py", line 266, in get_cov
    stat = layer_stats(
  File "/home/gridsan/shossain/EasyEdit/examples/../easyeditor/models/rome/layer_stats.py", line 197, in layer_stats
    model(**batch)
  File "/home/gridsan/shossain/.conda/envs/easy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gridsan/shossain/.conda/envs/easy/lib/python3.9/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/gridsan/shossain/.conda/envs/easy/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 1189, in forward
    outputs = self.model(
  File "/home/gridsan/shossain/.conda/envs/easy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gridsan/shossain/.conda/envs/easy/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 1001, in forward
    layer_outputs = decoder_layer(
  File "/home/gridsan/shossain/.conda/envs/easy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gridsan/shossain/.conda/envs/easy/lib/python3.9/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/gridsan/shossain/.conda/envs/easy/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 734, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/gridsan/shossain/.conda/envs/easy/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/gridsan/shossain/.conda/envs/easy/lib/python3.9/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/gridsan/shossain/.conda/envs/easy/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 424, in forward
    attn_weights = torch.matmul(query_states, key_states.transpose(2, 3)) / math.sqrt(self.head_dim)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.00 GiB (GPU 0; 31.74 GiB total capacity; 21.11 GiB already allocated; 4.61 GiB free; 26.75 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

I was able to run ROME successfully with model_parallel=True, and that has similar memory requirements from what I understand from your documentation. Do you have a sense of what the problem might be? I saw that there were recent bug fixes to MEMIT and I wonder if that may have affected the parallelism?

**Comment by zxlzr** [comment]
Sorry, due to a recent paper deadline, computational resources are currently limited. We will address this issue as soon as possible after the deadline.

**Comment by zxlzr** [comment]
hi, could you please provide more information? so we can help you address this issue.

**Comment by shariqahn** [comment]
Here is my hparams file with model_parallel set to true:
```
alg_name: "MEMIT"
# model_name: "./hugging_cache/llama-2-7b"
model_name: "/home/gridsan/shossain/EasyEdit/scr/models--meta-llama--Llama-2-7b-hf/snapshots/01c7f73d771dfac7d292323805ebc428287df4f9"
stats_dir: "./data/stats"
device: 0
layers: [4, 5, 6, 7, 8]
clamp_norm_factor: 4
layer_selection: "all"
fact_token: "subject_last"
v_num_grad_steps: 25
v_lr: 5e-1
v_loss_layer: 31
v_weight_decay: 1e-3
kl_factor: 0.0625
mom2_adjustment: true
mom2_update_weight: 15000
rewrite_module_tmp: "model.layers.{}.mlp.down_proj"
layer_module_tmp: "model.layers.{}"
mlp_module_tmp: "model.layers.{}.mlp"
attn_module_tmp: "model.layers.{}.self_attn"
ln_f_module: "model.norm"
lm_head_module: "lm_head"
mom2_dataset: "wikipedia"
mom2_n_samples: 100000
mom2_dtype: "float32"
# model_parallel: false
model_parallel: true
```
Here is the output of nvidia-smi shortly before the OOM error:
```
Wed Dec 18 12:20:01 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100-PCIE-32GB           On  | 00000000:86:00.0 Off |                  Off |
| N/A   43C    P0             160W / 150W |  14892MiB / 32768MiB |     65%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE-32GB           On  | 00000000:D8:00.0 Off |                  Off |
| N/A   37C    P0              38W / 150W |  14750MiB / 32768MiB |     14%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A    368434      C   python                                    14888MiB |
|    1   N/A  N/A    368434      C   python                                    14746MiB |
+---------------------------------------------------------------------------------------+
```
It appears that both GPUs are being used.

And the final error again:
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.00 GiB (GPU 0; 31.74 GiB total capacity; 21.11 GiB already allocated; 4.61 GiB free; 26.75 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

I also see this warning that I didn't see when running ROME in parallel for example:
```
  0%|          | 0/1000 [00:00<?, ?it/s][Ahuggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
```
It seems that the environment variable is adjusted as needed, but not sure if this is an indication of another problem.

**Comment by XeeKee** [comment]
Hi, we have recently optimized the multi-gpu code for MEMIT. You can try it again.

Our editing computation is set to default on gpu 0, and it is technically impossible to achieve completely uniform memory distribution. If you still encounter OOM issues, you can try enabling quantization when loading the model at this line: https://github.com/zjunlp/EasyEdit/blob/119c004395aab6f9101637ccc9e8d5520c084a09/easyeditor/editors/editor.py#L99.

**Comment by zxlzr** [comment]
hi, have you solved your issue yet?
