### ISSUE TITLE
Modify the MEND got error

### ISSUE THREAD

**Issue by LzyFischer** [zjunlp/EasyEdit#451]
The orginal MEND model has the following code in `easyeditor/trainer/algs/MEND.py`
```
 transformed_factors = {
            n: mend[str(tuple(get_shape(p)))](
                p.__x__, p.__delta__, param_idx(n, p)
            )
            for n, p in inner_params
        }
```
And it runs smoothly. However, when I build two mend named as `mend_encode` and `mend_decode`, and build them together
```
transformed_factors = {
            n: mend_encode[str(tuple(get_shape(p)))](
                p.__x__, p.__delta__, param_idx(n, p)
            )
            for n, p in inner_params
        }

transformed_factors = {
            n: mend_decode[str(tuple(get_shape(p)))](
                transformed_factors[n][0], transformed_factors[n][1], param_idx(n, p)
            )
            for i, (n, p) in enumerate(
                inner_params
            )
        }
```
The error below will appear. Can you give me some insights into this? Thanks!
```
 Traceback (most recent call last):
  File "/sfs/gpfs/tardis/project/uvadm/zhenyu/project/OpenBioMed/open_biomed/tasks/edit_task/capedit.py", line 94, in <module>
    trainer.run()
  File "/sfs/gpfs/tardis/project/uvadm/zhenyu/project/OpenBioMed/open_biomed/easyeditor/trainer/BaseTrainer.py", line 205, in run
    train_info = self.train_step(batch)
  File "/sfs/gpfs/tardis/project/uvadm/zhenyu/project/OpenBioMed/open_biomed/models/edit/multimodal_trainer.py", line 152, in train_step
    l_total, l_edit, l_loc, l_base, info_dict = self.edit_step(
  File "/sfs/gpfs/tardis/project/uvadm/zhenyu/project/OpenBioMed/open_biomed/models/edit/multimodal_trainer.py", line 98, in edit_step
    safe_backward(l_total_edit, self.model.outer_parameters(), self.config.accumulate_bs, allow_unused=True)
  File "/sfs/gpfs/tardis/project/uvadm/zhenyu/project/OpenBioMed/open_biomed/easyeditor/trainer/utils.py", line 84, in safe_backward
    grads = torch.autograd.grad(loss, parameters, allow_unused=allow_unused)
  File "/project/uvadm/zhenyu/miniconda3/envs/OpenBioMed/lib/python3.10/site-packages/torch/autograd/__init__.py", line 496, in grad
    result = _engine_run_backward(
  File "/project/uvadm/zhenyu/miniconda3/envs/OpenBioMed/lib/python3.10/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.
```

**Comment by zxlzr** [comment]
hi, do you have any further questions?
