### ISSUE TITLE
MEMIT Computation Time

### ISSUE THREAD

**Issue by shariqahn** [zjunlp/EasyEdit#455]
I am following up with https://github.com/zjunlp/EasyEdit/issues/449.

I am running MEMIT with quantization as you suggested. However, the computation time is very slow (~20s/it). Is this to be expected? I have included the logs below.

 ```
  0%|          | 0/1037 [00:00<?, ?it/s]MEMIT request sample: [When was the inception of IAAF Combined Events Challenge?] -> [ 2006]
Cached context templates [['{}'], ['The 2019 edition of the. {}', 'Therefore, it can be seen that the two. {}', 'Because the majority of the people who have a. {}', 'I’d like to share with you the. {}', "You're able to rely on Bathroom. {}"]]
Computing right vector (v)
Lookup index found: 14 | Sentence: When was the inception of IAAF Combined Events Challenge? 200 | Token: Challenge
Rewrite layer is 8
Tying optimization objective to 31
Recording initial value of v*
loss 3.233 = 3.233 + 0.0 + 0.0 avg prob of [ 2006] 0.039616815745830536
loss 3.29 = 3.212 + 0.078 + 0.0 avg prob of [ 2006] 0.0406082347035408
loss 3.134 = 3.078 + 0.055 + 0.0 avg prob of [ 2006] 0.04652901738882065
loss 2.926 = 2.873 + 0.053 + 0.0 avg prob of [ 2006] 0.0577276349067688
loss 2.446 = 2.394 + 0.051 + 0.0 avg prob of [ 2006] 0.09136156737804413
loss 2.14 = 2.09 + 0.05 + 0.0 avg prob of [ 2006] 0.12406286597251892
loss 1.707 = 1.657 + 0.049 + 0.0 avg prob of [ 2006] 0.19135968387126923
loss 1.077 = 1.027 + 0.05 + 0.0 avg prob of [ 2006] 0.35871586203575134
loss 0.383 = 0.325 + 0.057 + 0.0 avg prob of [ 2006] 0.7229785323143005
loss 0.137 = 0.069 + 0.068 + 0.0 avg prob of [ 2006] 0.9337589144706726
loss 0.081 = 0.018 + 0.063 + 0.0 avg prob of [ 2006] 0.9824641942977905
loss 0.069 = 0.007 + 0.061 + 0.0 avg prob of [ 2006] 0.9928245544433594
loss 0.078 = 0.004 + 0.074 + 0.0 avg prob of [ 2006] 0.9961426258087158
loss 0.059 = 0.003 + 0.056 + 0.0 avg prob of [ 2006] 0.9969296455383301
loss 0.058 = 0.002 + 0.056 + 0.0 avg prob of [ 2006] 0.9981862902641296
loss 0.055 = 0.001 + 0.054 + 0.0 avg prob of [ 2006] 0.9988991618156433
loss 0.05 = 0.001 + 0.049 + 0.0 avg prob of [ 2006] 0.9992554187774658
loss 0.049 = 0.001 + 0.048 + 0.0 avg prob of [ 2006] 0.999194860458374
Init norm 14.189818382263184 | Delta norm 56.759273529052734 | Target norm 58.391746520996094


LAYER 4

Writing 1 key/value pair(s) into layer 4
z error tensor(56.7470, device='cuda:0', grad_fn=<MeanBackward0>)
Retrieving covariance statistics for EasyEdit_scr_models--meta-llama--Llama-2-7b-hf_snapshots_01c7f73d771dfac7d292323805ebc428287df4f9 @ model.layers.4.mlp.down_proj.
Computing Cov locally....


  0%|          | 0/1000 [00:00<?, ?it/s][Ahuggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


  0%|          | 1/1000 [00:18<5:14:31, 18.89s/it][A

  0%|          | 2/1000 [00:36<5:03:05, 18.22s/it][A

  0%|          | 3/1000 [01:00<5:45:57, 20.82s/it][A
```

**Comment by zxlzr** [comment]
What GPU device are you using?

**Comment by pengzju** [comment]
It's quite normal to have an editing time close to 20s for a sample on V100 GPUs. You can refer to Table 5 in the paper "Editing Large Language Models: Problems, Methods, and Opportunities" for more details. With two V100s, the average duration is 14.5s.

**Comment by zxlzr** [comment]
hi, do you have any further questions?

**Comment by shariqahn** [comment]
I got the following error once the iterations I mentioned above were complete:
```
Traceback (most recent call last):
  File "EasyEdit/examples/run_zsre_llama2.py", line 97, in <module>
    metrics, edited_model, _ = editor.edit(
  File "EasyEdit/examples/../easyeditor/editors/editor.py", line 191, in edit
    return self.edit_requests(requests, sequential_edit, verbose, test_generation=test_generation, **kwargs)
  File "EasyEdit/examples/../easyeditor/editors/editor.py", line 381, in edit_requests
    edited_model, weights_copy, icl_examples = edit_func(request)
  File "EasyEdit/examples/../easyeditor/editors/editor.py", line 326, in edit_func
    edited_model, weights_copy = self.apply_algo(
  File "EasyEdit/examples/../easyeditor/models/memit/memit_main.py", line 46, in apply_memit_to_model
    deltas = execute_memit(model, tok, requests, hparams, cache_template=cache_template)
  File "EasyEdit/examples/../easyeditor/models/memit/memit_main.py", line 217, in execute_memit
    print("orig norm", torch.linalg.norm(weights[weight_name]))
RuntimeError: linalg.vector_norm: Expected a floating point or complex tensor as input. Got Char
```

**Comment by pengzju** [comment]
Hello, I just tried to reproduce the issue on llama2 and did not encounter the error you mentioned. However, from the error message, it seems that `weights[weight_name]` is not of tensor type. You can set a breakpoint here to try debugging.

**Comment by zxlzr** [comment]
do you have any further questions?

**Comment by shariqahn** [comment]
just to clarify, you were running the training with model_parallel=True and quantization?

**Comment by pengzju** [comment]
Yes, I run it on 2 A100 (80G) GPUs

**Comment by zxlzr** [comment]
hi, do you have any further questions？

**Comment by shariqahn** [comment]
No, I will debug this and let you know if I have further questions. Thank you!
