### ISSUE TITLE
Problem on running MEMIT for llama3.2-3b

### ISSUE THREAD

**Issue by Syon-Li** [zjunlp/EasyEdit#458]
Dear EasyEdit Team,

I got the following error when trying to run MEMIT for llama3.2-3b

```
Traceback (most recent call last):
  File "/Editing_baselines.py", line 533, in <module>
    main()
  File "/Editing_baselines.py", line 399, in main
    metrics, edited_model, weights_copy = editor.batch_edit(
  File "/EasyEdit/easyeditor/editors/editor.py", line 227, in batch_edit
    edited_model, weights_copy = self.apply_algo(
  File "/EasyEdit/easyeditor/models/memit/memit_main.py", line 46, in apply_memit_to_model
    deltas = execute_memit(model, tok, requests, hparams, cache_template=cache_template)
  File "/EasyEdit/easyeditor/models/memit/memit_main.py", line 137, in execute_memit
    cur_z = compute_z(
  File "/EasyEdit/easyeditor/models/memit/compute_z.py", line 149, in compute_z
    log_probs = torch.log_softmax(ln_f(full_repr) @ lm_w.to(full_repr.device) + lm_b.to(full_repr.device), dim=2)
RuntimeError: The size of tensor a (128256) must match the size of tensor b (3072) at non-singleton dimension 2
```

Can you confirm whether this is a bug in your code?

**Comment by zxlzr** [comment]
sorry, we will handle this issue as soon as possible.

**Comment by pengzju** [comment]
https://github.com/zjunlp/EasyEdit/commit/7e35bb1752d9bd1d5a8119a59a279dcc5282df05#diff-37751c17b0cd75afce0559f97c28e59f0a1cd662f4dc7eea5ba88fd1246166dcR21

**Comment by pengzju** [comment]
Perhaps this is useful, I feel it's because the wrong `lm_head_module `was chosen. Here I changed it to model.embed_tokens, you can give it a try? I can get it to work.

**Comment by zxlzr** [comment]
hi, have you solved your issue yet?

**Comment by Syon-Li** [comment]
Hi,

It works now, thanks for your response.

**Comment by Syon-Li** [comment]
Hi,

How much GPU memory would be required to calculate the Cov matrix for llama3.2-1b ?

I got the following message when running it for MEMIT:
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 252.98 GiB (GPU 1; 39.59 GiB total capacity; 20.04 GiB already allocated; 14.02 GiB free; 25.06 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Does the required memory seem too large?

**Comment by zxlzr** [comment]
Maybe you can try with larger GPU.

**Comment by Syon-Li** [comment]
> Dear EasyEdit Team,
> 
> I got the following error when trying to run MEMIT for llama3.2-3b
> 
> ```
> Traceback (most recent call last):
>   File "/Editing_baselines.py", line 533, in <module>
>     main()
>   File "/Editing_baselines.py", line 399, in main
>     metrics, edited_model, weights_copy = editor.batch_edit(
>   File "/EasyEdit/easyeditor/editors/editor.py", line 227, in batch_edit
>     edited_model, weights_copy = self.apply_algo(
>   File "/EasyEdit/easyeditor/models/memit/memit_main.py", line 46, in apply_memit_to_model
>     deltas = execute_memit(model, tok, requests, hparams, cache_template=cache_template)
>   File "/EasyEdit/easyeditor/models/memit/memit_main.py", line 137, in execute_memit
>     cur_z = compute_z(
>   File "/EasyEdit/easyeditor/models/memit/compute_z.py", line 149, in compute_z
>     log_probs = torch.log_softmax(ln_f(full_repr) @ lm_w.to(full_repr.device) + lm_b.to(full_repr.device), dim=2)
> RuntimeError: The size of tensor a (128256) must match the size of tensor b (3072) at non-singleton dimension 2
> ```
> 
> Can you confirm whether this is a bug in your code?

Hi, the same mistake occurs in other MEMIT-related methods, like EMMET, and PEMT (maybe there are others), could you help to fix it?

**Comment by pengzju** [comment]
Thank you again. I noticed that you solved this issue in #475. I have uploaded the corresponding hparam files.
